---
title: "Tablas de contingencia generalizadas para la Casen 2017 en un subset de 1000 registros."
author: "DI"
date: "09-11-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(markdown)
library(shiny)
library(shinythemes)
library(tidyverse)
library(magrittr)
library(lubridate)
library(plotly)
library(xts)
library(dygraphs)
library(kableExtra)
library(knitr)
library("readxl")
library(rsconnect)
library(dplyr)
library(summarytools)
library(epiDisplay)
#library(leaflet)
library(haven)
library(epiDisplay)
library("readxl")
library(hrbrthemes)
library(viridis)
library(viridisLite)
library(writexl)
library(plyr)
library(kableExtra)
library(knitr)
library(DescTools)
library(roperators)

# https://www.datacamp.com/community/tutorials/contingency-tables-r


oldw <- getOption("warn")
options(warn = -1)
```


# Promedios

```{r echo = FALSE, error=FALSE, warning=FALSE, message=FALSE}
casen_2006  <- read_xlsx("casen_2006_mil.xlsx")

head(casen_2006, 10)

```


```{r}
casen_2006$"Ingreso autónomo...13"
```

deben salir solo ceros:


```{r}
vec <- chr(casen_2006$"Ingreso autónomo...13") # make it a character vector first
vec %na<-% 0
vec
```



```{r}
vec = as.double(vec)  
vec
```




```{r}
aggregate(vec, list(casen_2006$"Identificación del hogar"), mean)


```


