---
title: "spss"
author: "Victor"
date: "05 de noviembre de 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(ggplot2)
library(ggpubr)
library(markdown)
library(shiny)
library(shinythemes)
library(tidyverse)
library(magrittr)
library(lubridate)
library(plotly)
library(xts)
library(dygraphs)
library(kableExtra)
library(knitr)
library("readxl")
library(rsconnect)
library(dplyr)
library(summarytools)
library(epiDisplay)
library(foreign)
```


```{r cars}
dataset = read.dta("casen2006.dta")
write.csv(dataset,"mydata2006.csv", row.names = FALSE)
```

```{r cars}
dataset = read_sav("casen2009Spss.sav")
write.csv(dataset,"mydata2009.csv", row.names = FALSE)
```


```{r cars}
dataset = read_sav("casen2011_octubre2011_enero2012_principal_08032013spss.sav")
write.csv(dataset,"mydata2011.csv", row.names = FALSE)
```


```{r cars}
dataset = read_sav("Casen 2017.sav")
write.csv(dataset,"mydata2017.csv", row.names = FALSE)
```


```{r}
dataset2006 <- read.csv('mydata2006.csv')
dataset2009 <- read.csv('mydata2009.csv')
dataset2011 <- read.csv('mydata2011.csv')

```


```{r}

dataset2006_sub <- dataset2006[1:1000,]
write.csv(dataset2006_sub,"mydata2006_sub.csv", row.names = FALSE)
dataset2006_sub <- read.csv('mydata2006_sub.csv')
dataset2006_sub
```

```{r}

dataset2009_sub <- dataset2009[1:1000,]
write.csv(dataset2009_sub,"mydata2009_sub.csv", row.names = FALSE)
dataset2009_sub <- read.csv('mydata2009_sub.csv')
dataset2009_sub
```

```{r}

dataset2011_sub <- dataset2011[1:1000,]
write.csv(dataset2011_sub,"mydata2011_sub.csv", row.names = FALSE)
dataset2011_sub <- read.csv('mydata2011_sub.csv')
dataset2011_sub
```




```{r}
colnames(dataset2006_sub)
```
















```{r}

dataset2006_sub <- read.csv('mydata2006_sub.csv')
dataset2006_sub
```






## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
write.csv(dataset,"Casen_2013_completa.csv", row.names = FALSE)
```

```{r}

#elements <- read.csv("Casen_2013_completa.csv")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
#colnames(elements)
```
elements$hacinamiento
elements$comuna
elements$sexo
elements$ecivil

```{r}
cross_tab = xtabs(elements$expc ~ unlist(elements$hacinamiento) + unlist(elements$comuna)+unlist(elements$sexo) + unlist(elements$ecivil), elements)
cross_tab
```


