---
title: "tablas"
author: "Victor"
date: "02 de diciembre de 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(ggplot2)
library(ggpubr)
library(markdown)
library(shiny)
library(shinythemes)
library(tidyverse)
library(magrittr)
library(lubridate)
library(plotly)
library(xts)
library(dygraphs)
library(kableExtra)
library(knitr)
library("readxl")
library(rsconnect)
library(dplyr)
library(summarytools)
library(epiDisplay)
#library(leaflet)
library(haven)
library(epiDisplay)
library("readxl")
library(expss)
library(hrbrthemes)
library(viridis)
library(viridisLite)
library(DescTools)
library(roperators)
library(shinycssloaders)
library(writexl)
library(vroom)
library(shinyWidgets)
library(BBmisc)


oldw <- getOption("warn")
options(warn = -1)

dataset2006  <- readRDS("dataset2006.rds")


data_codigos_comunales <- dataset2006


#dataset2006  <- dataset2006[1:100,]
dataset2006_col <- colnames(dataset2006)

data_2006_1_2_colnames <- colnames(dataset2006_col[2])

dataset06  <- readRDS("dataset06.rds")

dataset2009  <- readRDS("dataset2009.rds")

 dataset2009  <- dataset2009[1:100,]
dataset2009_col <- colnames(dataset2009)

# extraccion de las cabeceras para la carga de los filtros por categoria

data_2009_3_5 <- dataset2009[, c(4,6)]
data_2009_1_2_colnames <- colnames(data_2009_3_5)
data_2009_5_348 <- dataset2009[, 7:348]
data_2009_5_348_colnames <- colnames(data_2009_5_348)

dataset2011  <- readRDS("dataset2011.rds")

dataset2011  <- dataset2011[1:100,]
dataset2011_col <- colnames(dataset2011)

# extraccion de las cabeceras para la carga de los filtros por categoria

data_2011_3_5 <- dataset2011[, 1:6]
data_2011_1_2_colnames <- colnames(data_2011_3_5)
data_2011_5_348 <- dataset2011[, 7:348]
data_2011_5_348_colnames <- colnames(data_2011_5_348)

dataset2013  <- readRDS("dataset2013.rds")

# dataset2013  <- dataset2013[1:100,]
dataset2013_col <- colnames(dataset2013)

# extraccion de las cabeceras para la carga de los filtros por categoria

data_2013_3_5 <- dataset2013[, c(4,6)]
data_2013_1_2_colnames <- colnames(data_2013_3_5)
data_2013_5_348 <- dataset2013[, 7:348]
data_2013_5_348_colnames <- colnames(data_2013_5_348)

dataset2015  <- readRDS("dataset2015.rds")

dataset2015  <- dataset2015[1:100,]
dataset2015_col <- colnames(dataset2015)

# extraccion de las cabeceras para la carga de los filtros por categoria

data_2015_3_5 <- dataset2015[, c(4,6)]
data_2015_1_2_colnames <- colnames(data_2015_3_5)
data_2015_5_348 <- dataset2015[, 7:348]
data_2015_5_348_colnames <- colnames(data_2015_5_348)

##################   2017 ##############################
dataset2017  <- readRDS("dataset2017.rds")

dataset2017  <- dataset2017[1:100,]
dataset2017_col <- colnames(dataset2017)
```
```{r}
dataset2017  <- readRDS("dataset2017.rds")

#dataset2017  <- dataset2017[1:100,]
dataset2017_col <- colnames(dataset2017)
```


```{r}
  

    #ab <- dataset2011_react()
    #ab <- data_codigos_comunales_2011
    
    ab  <- readRDS("dataset2011.rds")
    #ab <- ab[1:100, ]
    data_code <- ab[ , c("segmento", "comuna")]
    
    names(data_code)[2] <- "unlist.a."
    data_code <- distinct(data_code , unlist.a., .keep_all = TRUE)
    data_code <- data_code %>% mutate(unlist.a. = str_squish(unlist.a.))
    
    
    data_code <- data_code %>% mutate(codigo = case_when(as.integer(segmento / 10000000) == 0 ~ as.integer(segmento/ 10000)
                                                         , as.integer(segmento / 10000000) <17 ~ as.integer(segmento / 10000)
                                                         
    ))
    
    data_code <- subset( data_code, select = -segmento )
    data_code[171,2]<-16101
    data_code[172,2]<-16102
    data_code[173,2]<-16202
    data_code[174,2]<-16203
    data_code[175,2]<-16302
    data_code[176,2]<-16103
    data_code[177,2]<-16104
    data_code[178,2]<-16204
    data_code[179,2]<-16303
    data_code[180,2]<-16105
    data_code[181,2]<-16106
    data_code[182,2]<-16205
    data_code[183,2]<-16107
    data_code[184,2]<-16201
    data_code[185,2]<-16206
    data_code[186,2]<-16301
    data_code[187,2]<-16304
    data_code[188,2]<-16108
    data_code[189,2]<-16305
    data_code[190,2]<-16207
    data_code[191,2]<-16109
    
    # d <- input$p2011_primerav
    # e <- input$p2011_segundav
    # f <- input$p2011_tercerav
    # g <- input$p2011_cuartav
    
    a <- ab$comuna
    b <- ab$r6
    c <- ab$e1
    d <- ab$sexo
    
    
    
      cross_tab =  xtabs(ab$expc_full ~ unlist(a) + unlist(b)+unlist(c)+unlist(d),aggregate(ab$expc_full ~ unlist(a)+unlist(b)+unlist(c)+unlist(d),ab,mean))
   
    
    tabla <- as.data.frame(cross_tab)
    
    d <-tabla[!(tabla$Freq == 0),]
    
    d$anio <- "2011"
    
    #df1 = merge( x = d1, y = data_code1, by = "a")  
    df = merge( x = d, y = data_code, by = "unlist.a.", all.x = TRUE)  
    df
    #write.csv(df,"etnia_anal_sexo_2011.csv", row.names = FALSE)
```
```{r}
write.csv(data_code,"comunas_2006_nueva5.csv", row.names = FALSE)
```

```{r}
data_code[270,2]<-11201
    data_code[8,2]<-15101
    data_code[178,2]<-16102
    data_code[9,2]<-15102
    data_code[2,2]<-1402
    data_code[177,2]<-16101
    data_code[182,2]<-16103
    data_code[96,2]<-6303
    data_code[179,2]<-16202
    data_code[180,2]<-16203
    data_code[181,2]<-16302
    data_code[3,2]<-1403
    data_code[287,2]<-13104
    data_code[261,2]<-14102
    data_code[183,2]<-16104
    data_code[262,2]<-14202
    data_code[11,2]<-15202
    data_code[4,2]<-1404
    data_code[292,2]<-13110
    data_code[263,2]<-14201
    data_code[264,2]<-14203
    data_code[265,2]<-14103
    data_code[66,2]<-5802
    data_code[266,2]<-14104
    data_code[267,2]<-14105
    data_code[268,2]<-14106
    data_code[89,2]<-6110
    data_code[184,2]<-16204
    data_code[185,2]<-16303
    data_code[68,2]<-5803
    data_code[271,2]<-14107
    data_code[272,2]<-14108
    data_code[186,2]<-16105
    data_code[5,2]<-1405
    data_code[187,2]<-16106
    data_code[188,2]<-16205
    data_code[6,2]<-1401
    data_code[10,2]<-15201
    data_code[246,2]<-16107
    data_code[49,2]<-5801
    data_code[92,2]<-6114
    data_code[190,2]<-16201
    data_code[191,2]<-16206
    data_code[273,2]<-14204
    data_code[192,2]<-16301
    data_code[193,2]<-16304
    data_code[194,2]<-16108
    data_code[195,2]<-16305
    data_code[286,2]<-13505
    data_code[196,2]<-16207
    data_code[260,2]<-14101
    data_code[51,2]<-5804
    data_code[197,2]<-16109
    write.csv(data_code,"comunas_2006_nueva6.csv", row.names = FALSE)
```





```{r}
  
          
          
          ab <- dataset2013
          
          a <- ab$comuna
          b <- ab$e1
          c <- ab$sexo 
          d <- ab$ecivil 
        
          cross_tab = table(a, b, c, d)
         
          # 
          tabla <- as.data.frame(cross_tab)
         
          ab <- data_codigos_comunales
         
           data_code <- ab[  , c("seg", "comuna")]
          # 
           names(data_code)[2] <- "a"
           data_code <- distinct(data_code , a, .keep_all = TRUE)
          # 
          data_code <- data_code %>% mutate(a = str_squish(a))
         
          # 
          # # https://stackoverflow.com/questions/22337394/dplyr-mutate-with-conditional-values/22337459
          # 
          data_code  <-  data_code  %>% mutate(codigo = case_when(as.integer(seg / 1000) > 0 ~ as.integer(seg / 1000), as.integer(seg / 10000) == 141 ~ as.integer(seg / 100)

                                                                  , as.integer(seg / 10000) == 142 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 101 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 102 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 103 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 104 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 111 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 112 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 113 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 114 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 121 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 122 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 123 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 124 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 131 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 132 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 133 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 134 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 135 ~ as.integer(seg / 100)
                                                                  , as.integer(seg / 10000) == 136 ~ as.integer(seg / 100)
          ))

          data_code <- subset( data_code, select = -seg )
          data_code
          
          d <-tabla[!(tabla$Freq == 0),]

          d$anio <- "2013"
          d
           df = merge( x = d, y = data_code, by = "a", all.x = TRUE)
            # df
            
          # return(tabla)
```
```{r}
l <- colnames(dataset2013)
l
```
```{r}
l <- colnames(data_code)
l
```
```{r}
s <- dataset2015[,736]
s
```



```{r}
df
```


```{r}
r0 <- data_code[4,1]

r0
```

```{r}
r1 <- d[5,1]
r1 <- as.character(r1)

r1
```

```{r}
if(r0 != r1){
  print("los registros son diferentes")
}
```
